/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamOverviewRouteImport } from './routes/team-overview'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiscountSettingsRouteImport } from './routes/discount-settings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AiLoggerRouteImport } from './routes/ai-logger'
import { Route as AdminCalendarRouteImport } from './routes/admin-calendar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as QuotesIndexRouteImport } from './routes/quotes.index'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as RequestsCreateRouteImport } from './routes/requests.create'
import { Route as QuotesBuildRouteImport } from './routes/quotes.build'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'

const TeamOverviewRoute = TeamOverviewRouteImport.update({
  id: '/team-overview',
  path: '/team-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountSettingsRoute = DiscountSettingsRouteImport.update({
  id: '/discount-settings',
  path: '/discount-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLoggerRoute = AiLoggerRouteImport.update({
  id: '/ai-logger',
  path: '/ai-logger',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/admin-calendar',
  path: '/admin-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesIndexRoute = QuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsCreateRoute = RequestsCreateRouteImport.update({
  id: '/requests/create',
  path: '/requests/create',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesBuildRoute = QuotesBuildRouteImport.update({
  id: '/quotes/build',
  path: '/quotes/build',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-calendar': typeof AdminCalendarRoute
  '/ai-logger': typeof AiLoggerRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/discount-settings': typeof DiscountSettingsRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/tasks': typeof TasksRoute
  '/team-overview': typeof TeamOverviewRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/quotes/build': typeof QuotesBuildRoute
  '/requests/create': typeof RequestsCreateRoute
  '/leads/': typeof LeadsIndexRoute
  '/quotes/': typeof QuotesIndexRoute
  '/requests/': typeof RequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-calendar': typeof AdminCalendarRoute
  '/ai-logger': typeof AiLoggerRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/discount-settings': typeof DiscountSettingsRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/tasks': typeof TasksRoute
  '/team-overview': typeof TeamOverviewRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/quotes/build': typeof QuotesBuildRoute
  '/requests/create': typeof RequestsCreateRoute
  '/leads': typeof LeadsIndexRoute
  '/quotes': typeof QuotesIndexRoute
  '/requests': typeof RequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-calendar': typeof AdminCalendarRoute
  '/ai-logger': typeof AiLoggerRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/discount-settings': typeof DiscountSettingsRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/tasks': typeof TasksRoute
  '/team-overview': typeof TeamOverviewRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/quotes/build': typeof QuotesBuildRoute
  '/requests/create': typeof RequestsCreateRoute
  '/leads/': typeof LeadsIndexRoute
  '/quotes/': typeof QuotesIndexRoute
  '/requests/': typeof RequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-calendar'
    | '/ai-logger'
    | '/calendar'
    | '/dashboard'
    | '/discount-settings'
    | '/login'
    | '/pipeline'
    | '/products'
    | '/reports'
    | '/tasks'
    | '/team-overview'
    | '/leads/$leadId'
    | '/quotes/build'
    | '/requests/create'
    | '/leads/'
    | '/quotes/'
    | '/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-calendar'
    | '/ai-logger'
    | '/calendar'
    | '/dashboard'
    | '/discount-settings'
    | '/login'
    | '/pipeline'
    | '/products'
    | '/reports'
    | '/tasks'
    | '/team-overview'
    | '/leads/$leadId'
    | '/quotes/build'
    | '/requests/create'
    | '/leads'
    | '/quotes'
    | '/requests'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-calendar'
    | '/ai-logger'
    | '/calendar'
    | '/dashboard'
    | '/discount-settings'
    | '/login'
    | '/pipeline'
    | '/products'
    | '/reports'
    | '/tasks'
    | '/team-overview'
    | '/leads/$leadId'
    | '/quotes/build'
    | '/requests/create'
    | '/leads/'
    | '/quotes/'
    | '/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AiLoggerRoute: typeof AiLoggerRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  DiscountSettingsRoute: typeof DiscountSettingsRoute
  LoginRoute: typeof LoginRoute
  PipelineRoute: typeof PipelineRoute
  ProductsRoute: typeof ProductsRoute
  ReportsRoute: typeof ReportsRoute
  TasksRoute: typeof TasksRoute
  TeamOverviewRoute: typeof TeamOverviewRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  QuotesBuildRoute: typeof QuotesBuildRoute
  RequestsCreateRoute: typeof RequestsCreateRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  QuotesIndexRoute: typeof QuotesIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team-overview': {
      id: '/team-overview'
      path: '/team-overview'
      fullPath: '/team-overview'
      preLoaderRoute: typeof TeamOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discount-settings': {
      id: '/discount-settings'
      path: '/discount-settings'
      fullPath: '/discount-settings'
      preLoaderRoute: typeof DiscountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-logger': {
      id: '/ai-logger'
      path: '/ai-logger'
      fullPath: '/ai-logger'
      preLoaderRoute: typeof AiLoggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-calendar': {
      id: '/admin-calendar'
      path: '/admin-calendar'
      fullPath: '/admin-calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/': {
      id: '/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof QuotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/create': {
      id: '/requests/create'
      path: '/requests/create'
      fullPath: '/requests/create'
      preLoaderRoute: typeof RequestsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/build': {
      id: '/quotes/build'
      path: '/quotes/build'
      fullPath: '/quotes/build'
      preLoaderRoute: typeof QuotesBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AiLoggerRoute: AiLoggerRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  DiscountSettingsRoute: DiscountSettingsRoute,
  LoginRoute: LoginRoute,
  PipelineRoute: PipelineRoute,
  ProductsRoute: ProductsRoute,
  ReportsRoute: ReportsRoute,
  TasksRoute: TasksRoute,
  TeamOverviewRoute: TeamOverviewRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  QuotesBuildRoute: QuotesBuildRoute,
  RequestsCreateRoute: RequestsCreateRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  QuotesIndexRoute: QuotesIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
